"""
Comprehensive Multilingual Lexicon Generator and Seeder.
Generates 20-30+ authentic words per proficiency level (A1, A2, B1, B2, C1, C2)
across all 13 supported languages covering Conjunctions, Verbs, Nouns, Adjectives, Adverbs, Prepositions, and Phrases.
"""

import json
import logging
import asyncio
from pathlib import Path
from sqlalchemy import select, delete
from sqlalchemy.ext.asyncio import AsyncSession
from app.models import CEFRLevel, Language, Word
from app.core.database import get_session_maker

logger = logging.getLogger("linguamaxima.bulk_seed")

DATA_DIR = Path(__file__).parent / "data"

# Standard vocabulary template per language covering all levels (A1..C2) with multiple POS and authentic usage examples
LEXICON_DEFINITIONS = {
    # -------------------------------------------------------------------------
    # 1. GERMAN (de)
    # -------------------------------------------------------------------------
    "de": [
        # --- A1 (Basic Beginner) ---
        {"lemma": "und", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ʊnt", "translation": "and / dan", "definition": "Coordinating conjunction joining words or clauses.", "example_sentence": "Ich habe einen Hund und eine Katze.", "example_translation": "I have a dog and a cat.", "frequency_rank": 2},
        {"lemma": "aber", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ˈaːbɐ", "translation": "but / namun", "definition": "Coordinating conjunction expressing opposition or restriction.", "example_sentence": "Er ist müde, aber er arbeitet weiter.", "example_translation": "He is tired, but he keeps working.", "frequency_rank": 14},
        {"lemma": "oder", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ˈoːdɐ", "translation": "or / atau", "definition": "Conjunction presenting an alternative.", "example_sentence": "Möchtest du Tee oder Kaffee trinken?", "example_translation": "Would you like to drink tea or coffee?", "frequency_rank": 22},
        {"lemma": "denn", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "dɛn", "translation": "for / because / sebab", "definition": "Coordinating conjunction explaining a reason.", "example_sentence": "Wir bleiben drinnen, denn es regnet stark.", "example_translation": "We stay inside, for it is raining heavily.", "frequency_rank": 28},
        {"lemma": "weil", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "vaɪ̯l", "translation": "because / karena", "definition": "Subordinating conjunction of cause (verb goes to end).", "example_sentence": "Ich lerne Deutsch, weil ich in Wien studieren möchte.", "example_translation": "I am learning German because I want to study in Vienna.", "frequency_rank": 35},
        {"lemma": "wenn", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "vɛn", "translation": "when / if / jika / ketika", "definition": "Conditional or temporal subordinating conjunction.", "example_sentence": "Wenn das Wetter schön ist, gehen wir spazieren.", "example_translation": "When the weather is nice, we go for a walk.", "frequency_rank": 18},
        {"lemma": "dass", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "das", "translation": "that / bahwa", "definition": "Subordinating conjunction introducing a noun clause.", "example_sentence": "Ich weiß, dass du recht hast.", "example_translation": "I know that you are right.", "frequency_rank": 9},
        {"lemma": "Haus", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "das", "phonetic": "haʊ̯s", "translation": "house / rumah", "definition": "A building for living.", "example_sentence": "Das Haus hat einen schönen Garten.", "example_translation": "The house has a beautiful garden.", "frequency_rank": 70},
        {"lemma": "Freund", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "der", "phonetic": "fʁɔɪ̯nt", "translation": "friend / teman", "definition": "A close companion.", "example_sentence": "Mein Freund Lukas wohnt in Berlin.", "example_translation": "My friend Lukas lives in Berlin.", "frequency_rank": 85},
        {"lemma": "Stadt", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "die", "phonetic": "ʃtat", "translation": "city / kota", "definition": "A large human settlement.", "example_sentence": "München ist eine sehr lebendige Stadt.", "example_translation": "Munich is a very lively city.", "frequency_rank": 60},
        {"lemma": "kommen", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "ˈkɔmən", "translation": "to come / datang", "definition": "Move toward a destination.", "example_sentence": "Wann kommst du heute nach Hause?", "example_translation": "When are you coming home today?", "frequency_rank": 25},
        {"lemma": "gehen", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "ˈɡeːən", "translation": "to go / to walk / pergi", "definition": "Move on foot or travel.", "example_sentence": "Wir gehen jeden Morgen in den Park.", "example_translation": "We go to the park every morning.", "frequency_rank": 20},
        {"lemma": "essen", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "ˈɛsn̩", "translation": "to eat / makan", "definition": "Consume food.", "example_sentence": "Wir essen am Abend frisches Brot und Käse.", "example_translation": "In the evening we eat fresh bread and cheese.", "frequency_rank": 45},
        {"lemma": "schön", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adjective", "gender": None, "phonetic": "ʃøːn", "translation": "beautiful / nice / indah", "definition": "Pleasing to the senses.", "example_sentence": "Heute ist ein sehr schöner Tag.", "example_translation": "Today is a very beautiful day.", "frequency_rank": 55},
        {"lemma": "groß", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adjective", "gender": None, "phonetic": "ɡʁoːs", "translation": "big / large / tall / besar", "definition": "Of considerable size or height.", "example_sentence": "Der Hauptbahnhof ist riesig und groß.", "example_translation": "The central train station is huge and large.", "frequency_rank": 30},
        {"lemma": "gut", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adjective", "gender": None, "phonetic": "ɡuːt", "translation": "good / baik / bagus", "definition": "Satisfactory or desirable quality.", "example_sentence": "Das Essen schmeckt wirklich gut.", "example_translation": "The food tastes really good.", "frequency_rank": 12},
        {"lemma": "heute", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈhɔɪ̯tə", "translation": "today / hari ini", "definition": "On this current day.", "example_sentence": "Heute habe ich keinen Unterricht.", "example_translation": "Today I have no classes.", "frequency_rank": 40},
        {"lemma": "hier", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adverb", "gender": None, "phonetic": "hiːɐ̯", "translation": "here / di sini", "definition": "In this specific place.", "example_sentence": "Hier kann man sehr gut Deutsch lernen.", "example_translation": "Here one can learn German very well.", "frequency_rank": 15},
        {"lemma": "in", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "preposition", "gender": None, "phonetic": "ɪn", "translation": "in / inside / di dalam", "definition": "Preposition indicating location or time.", "example_sentence": "Wir wohnen in einer gemütlichen Wohnung.", "example_translation": "We live in a cozy apartment.", "frequency_rank": 4},
        {"lemma": "mit", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "preposition", "gender": None, "phonetic": "mɪt", "translation": "with / dengan", "definition": "Preposition indicating accompaniment (dative).", "example_sentence": "Ich fahre mit dem Bus zur Arbeit.", "example_translation": "I travel to work by bus.", "frequency_rank": 8},

        # --- A2 (Elementary) ---
        {"lemma": "ob", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɔp", "translation": "whether / if / apakah", "definition": "Conjunction introducing an indirect question.", "example_sentence": "Ich frage mich, ob er morgen kommt.", "example_translation": "I wonder whether he is coming tomorrow.", "frequency_rank": 95},
        {"lemma": "als", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "conjunction", "gender": None, "phonetic": "als", "translation": "when (past) / as / than / ketika", "definition": "Temporal conjunction for single past events or comparative.", "example_sentence": "Als ich ein Kind war, spielte ich oft draußen.", "example_translation": "When I was a child, I often played outside.", "frequency_rank": 16},
        {"lemma": "damit", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "conjunction", "gender": None, "phonetic": "daˈmɪt", "translation": "so that / in order that / agar", "definition": "Subordinating conjunction of purpose.", "example_sentence": "Er lernt fleißig, damit er die Prüfung besteht.", "example_translation": "He studies diligently so that he passes the exam.", "frequency_rank": 115},
        {"lemma": "Erfahrung", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "noun", "gender": "die", "phonetic": "ɛɐ̯ˈfaːʁʊŋ", "translation": "experience / pengalaman", "definition": "Practical contact with facts or events.", "example_sentence": "Sie hat bereits viel Erfahrung im Beruf.", "example_translation": "She already has a lot of experience on the job.", "frequency_rank": 210},
        {"lemma": "Entscheidung", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "noun", "gender": "die", "phonetic": "ɛntˈʃaɪ̯dʊŋ", "translation": "decision / keputusan", "definition": "A conclusion or choice reached after consideration.", "example_sentence": "Es war eine kluge Entscheidung.", "example_translation": "It was a wise decision.", "frequency_rank": 240},
        {"lemma": "Unterschied", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "noun", "gender": "der", "phonetic": "ˈʊntɐˌʃiːt", "translation": "difference / perbedaan", "definition": "A point or way in which people or things are not the same.", "example_sentence": "Was ist der Unterschied zwischen diesen beiden Wörtern?", "example_translation": "What is the difference between these two words?", "frequency_rank": 260},
        {"lemma": "entscheiden", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "verb", "gender": None, "phonetic": "ɛntˈʃaɪ̯dn̩", "translation": "to decide / memutuskan", "definition": "Make a choice.", "example_sentence": "Wir müssen uns bald entscheiden.", "example_translation": "We must decide soon.", "frequency_rank": 180},
        {"lemma": "beschreiben", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "verb", "gender": None, "phonetic": "bəˈʃʁaɪ̯bn̩", "translation": "to describe / menggambarkan", "definition": "Give a detailed account in words.", "example_sentence": "Können Sie das Bild bitte genauer beschreiben?", "example_translation": "Could you please describe the picture in more detail?", "frequency_rank": 220},
        {"lemma": "verstehen", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "verb", "gender": None, "phonetic": "fɛɐ̯ˈʃteːən", "translation": "to understand / memahami", "definition": "Perceive the intended meaning of.", "example_sentence": "Ich verstehe die Erklärung des Lehrers sehr gut.", "example_translation": "I understand the teacher's explanation very well.", "frequency_rank": 75},
        {"lemma": "wichtig", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈvɪçtɪç", "translation": "important / penting", "definition": "Of great significance or value.", "example_sentence": "Gesundheit ist das Wichtigste im Leben.", "example_translation": "Health is the most important thing in life.", "frequency_rank": 88},
        {"lemma": "einfach", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈaɪ̯nfax", "translation": "simple / easy / mudah", "definition": "Easily understood or done.", "example_sentence": "Die Aufgabe war erstaunlich einfach.", "example_translation": "The task was surprisingly easy.", "frequency_rank": 92},
        {"lemma": "plötzlich", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈplœtslɪç", "translation": "suddenly / tiba-tiba", "definition": "Quickly and unexpectedly.", "example_sentence": "Plötzlich begann es heftig zu schneien.", "example_translation": "Suddenly it began to snow heavily.", "frequency_rank": 205},
        {"lemma": "trotzdem", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈtʁɔtsdəm", "translation": "nevertheless / anyway / meskipun demikian", "definition": "Adverb expressing concession.", "example_sentence": "Es war kalt, trotzdem ging er schwimmen.", "example_translation": "It was cold, nevertheless he went swimming.", "frequency_rank": 190},
        {"lemma": "ohne", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "preposition", "gender": None, "phonetic": "ˈoːnə", "translation": "without / tanpa", "definition": "Preposition requiring accusative.", "example_sentence": "Ohne Fleiß kein Preis.", "example_translation": "No pain, no gain (Without effort no reward).", "frequency_rank": 68},
        {"lemma": "durch", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "preposition", "gender": None, "phonetic": "dʊʁç", "translation": "through / by / melalui", "definition": "Preposition indicating movement or agency.", "example_sentence": "Wir gingen durch den dichten Wald.", "example_translation": "We walked through the dense forest.", "frequency_rank": 32},

        # --- B1 (Intermediate) ---
        {"lemma": "obwohl", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɔpˈvoːl", "translation": "although / even though / meskipun", "definition": "Subordinating conjunction expressing concession.", "example_sentence": "Er geht spazieren, obwohl es stark regnet.", "example_translation": "He goes for a walk, although it is raining heavily.", "frequency_rank": 210},
        {"lemma": "während", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ˈvɛːʁənt", "translation": "while / whereas / sementara", "definition": "Conjunction expressing simultaneous actions or contrast.", "example_sentence": "Sie las ein Buch, während er das Abendessen kochte.", "example_translation": "She read a book while he cooked dinner.", "frequency_rank": 320},
        {"lemma": "sodass", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "conjunction", "gender": None, "phonetic": "zoːˈdas", "translation": "so that / with the result that / sehingga", "definition": "Conjunction expressing a consequence.", "example_sentence": "Er sprach sehr leise, sodass ihn niemand verstand.", "example_translation": "He spoke very quietly, so that nobody understood him.", "frequency_rank": 340},
        {"lemma": "Herausforderung", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "noun", "gender": "die", "phonetic": "hɛˈʁaʊ̯sˌfɔʁdəʁʊŋ", "translation": "challenge / tantangan", "definition": "A demanding task or situation.", "example_sentence": "Das neue Projekt ist eine große Herausforderung für das Team.", "example_translation": "The new project is a major challenge for the team.", "frequency_rank": 410},
        {"lemma": "Umwelt", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "noun", "gender": "die", "phonetic": "ˈʊmvɛlt", "translation": "environment / lingkungan hidup", "definition": "The surrounding natural world.", "example_sentence": "Der Schutz der Umwelt geht uns alle an.", "example_translation": "The protection of the environment concerns all of us.", "frequency_rank": 380},
        {"lemma": "Möglichkeit", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "noun", "gender": "die", "phonetic": "ˈmøːklɪçkaɪ̯t", "translation": "possibility / opportunity / kemungkinan", "definition": "A chance or option.", "example_sentence": "Wir haben viele Möglichkeiten, das Problem zu lösen.", "example_translation": "We have many possibilities to solve the problem.", "frequency_rank": 290},
        {"lemma": "verbessern", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "verb", "gender": None, "phonetic": "fɛɐ̯ˈbɛsɐn", "translation": "to improve / meningkatkan", "definition": "Make or become better.", "example_sentence": "Tägliches Üben hilft, die Sprachkenntnisse zu verbessern.", "example_translation": "Daily practice helps improve language skills.", "frequency_rank": 350},
        {"lemma": "entwickeln", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "verb", "gender": None, "phonetic": "ɛntˈvɪkln̩", "translation": "to develop / mengembangkan", "definition": "Grow or cause to grow and become more advanced.", "example_sentence": "Forscher entwickeln neue Technologien für erneuerbare Energien.", "example_translation": "Researchers are developing new technologies for renewable energy.", "frequency_rank": 270},
        {"lemma": "überzeugen", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "verb", "gender": None, "phonetic": "yːbɐˈtsɔɪ̯ɡn̩", "translation": "to convince / persuade / meyakinkan", "definition": "Cause someone to believe firmly in the truth of something.", "example_sentence": "Ihre fundierten Argumente haben das gesamte Gremium überzeugt.", "example_translation": "Her well-founded arguments convinced the entire committee.", "frequency_rank": 430},
        {"lemma": "erfolgreich", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "adjective", "gender": None, "phonetic": "ɛɐ̯ˈfɔlkʁaɪ̯ç", "translation": "successful / sukses / berhasil", "definition": "Accomplishing an aim or purpose.", "example_sentence": "Das Projekt wurde erfolgreich abgeschlossen.", "example_translation": "The project was successfully concluded.", "frequency_rank": 310},
        {"lemma": "deutlich", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈdɔɪ̯tlɪç", "translation": "clear / distinct / jelas", "definition": "Easily seen, heard, or understood.", "example_sentence": "Es gibt einen deutlichen Unterschied im Ergebnis.", "example_translation": "There is a distinct difference in the outcome.", "frequency_rank": 250},
        {"lemma": "außerdem", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈaʊ̯sɐˌdeːm", "translation": "besides / furthermore / selain itu", "definition": "In addition to.", "example_sentence": "Das Buch ist spannend, und außerdem lernt man viel.", "example_translation": "The book is exciting, and furthermore one learns a lot.", "frequency_rank": 220},

        # --- B2 (Upper Intermediate) ---
        {"lemma": "nachdem", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "conjunction", "gender": None, "phonetic": "naːxˈdeːm", "translation": "after / sesudah", "definition": "Conjunction indicating prior completed action.", "example_sentence": "Nachdem er sein Studium abgeschlossen hatte, zog er nach Berlin.", "example_translation": "After he had finished his studies, he moved to Berlin.", "frequency_rank": 480},
        {"lemma": "indem", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɪnˈdeːm", "translation": "by doing / in that / dengan cara", "definition": "Modal conjunction indicating the means or method.", "example_sentence": "Man lernt eine Sprache am besten, indem man sie täglich spricht.", "example_translation": "One learns a language best by speaking it daily.", "frequency_rank": 510},
        {"lemma": "je ... desto", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "conjunction", "gender": None, "phonetic": "jeː ... ˈdɛstoː", "translation": "the more ... the more / makin ... makin", "definition": "Proportional correlative conjunction pair.", "example_sentence": "Je mehr man liest, desto größer wird der Wortschatz.", "example_translation": "The more you read, the larger your vocabulary becomes.", "frequency_rank": 460},
        {"lemma": "Nachhaltigkeit", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "noun", "gender": "die", "phonetic": "ˈnaːxˌhaltɪçkaɪ̯t", "translation": "sustainability / keberlanjutan", "definition": "Maintenance of ecological and economic balance.", "example_sentence": "Ökologische Nachhaltigkeit steht im Zentrum moderner Stadtplanung.", "example_translation": "Ecological sustainability is at the center of modern urban planning.", "frequency_rank": 620},
        {"lemma": "Zusammenhang", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "noun", "gender": "der", "phonetic": "tsuˈzamənˌhaŋ", "translation": "context / connection / kaitan", "definition": "The interrelated conditions in which something exists.", "example_sentence": "In diesem Zusammenhang müssen wir alle Faktoren berücksichtigen.", "example_translation": "In this context we must consider all factors.", "frequency_rank": 540},
        {"lemma": "gewährleisten", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "verb", "gender": None, "phonetic": "ɡəˈvɛːɐ̯ˌlaɪ̯stn̩", "translation": "to guarantee / ensure / menjamin", "definition": "Provide a guarantee or ensure safety.", "example_sentence": "Neue Gesetze gewährleisten den Schutz persönlicher Daten.", "example_translation": "New laws guarantee the protection of personal data.", "frequency_rank": 750},
        {"lemma": "berücksichtigen", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "verb", "gender": None, "phonetic": "bəˈʁʏkˌzɪçtɪɡn̩", "translation": "to take into account / consider / mempertimbangkan", "definition": "Take into consideration.", "example_sentence": "Wir sollten die Wünsche der Kunden stärker berücksichtigen.", "example_translation": "We should take customers' wishes into greater account.", "frequency_rank": 580},
        {"lemma": "wesentlich", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈveːzn̩tlɪç", "translation": "essential / substantial / mendasar", "definition": "Of the greatest importance; fundamental.", "example_sentence": "Das ist ein wesentlicher Bestandteil des Erfolgs.", "example_translation": "That is an essential component of success.", "frequency_rank": 490},
        {"lemma": "folglich", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈfɔlklɪç", "translation": "consequently / as a result / oleh karena itu", "definition": "As a logical consequence.", "example_sentence": "Die Einnahmen sanken; folglich mussten Ausgaben gekürzt werden.", "example_translation": "Revenues fell; consequently, expenditures had to be cut.", "frequency_rank": 640},

        # --- C1 (Advanced) ---
        {"lemma": "insofern", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɪnzoˈfɛʁn", "translation": "insofar as / to that extent / sejauh", "definition": "Adverbial conjunction indicating extent or degree.", "example_sentence": "Der Vorschlag ist insofern vorteilhaft, als er Ressourcen spart.", "example_translation": "The proposal is advantageous insofar as it saves resources.", "frequency_rank": 880},
        {"lemma": "angesichts", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "preposition", "gender": None, "phonetic": "ˈanɡəˌzɪçts", "translation": "in view of / considering / mengingat", "definition": "Preposition governing genitive case.", "example_sentence": "Angesichts der aktuellen Lage müssen wir sofort handeln.", "example_translation": "In view of the current situation, we must act immediately.", "frequency_rank": 910},
        {"lemma": "Erkenntnis", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "noun", "gender": "die", "phonetic": "ɛɐ̯ˈkɛntnɪs", "translation": "insight / scientific finding / wawasan", "definition": "A deep understanding gained through systematic study.", "example_sentence": "Die neuesten wissenschaftlichen Erkenntnisse stützen die Hypothese.", "example_translation": "The latest scientific findings support the hypothesis.", "frequency_rank": 920},
        {"lemma": "Plausibilität", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "noun", "gender": "die", "phonetic": "plaʊ̯zibiˈliːtɛːt", "translation": "plausibility / masuk akal", "definition": "The quality of seeming reasonable or probable.", "example_sentence": "Die Plausibilität der Argumentation wurde von Experten bestätigt.", "example_translation": "The plausibility of the reasoning was confirmed by experts.", "frequency_rank": 1050},
        {"lemma": "hervorheben", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "verb", "gender": None, "phonetic": "hɛɐ̯ˈfoːɐ̯ˌheːbn̩", "translation": "to highlight / emphasize / menekankan", "definition": "Draw special attention to.", "example_sentence": "Der Redner hob die Wichtigkeit internationaler Kooperation hervor.", "example_translation": "The speaker highlighted the importance of international cooperation.", "frequency_rank": 980},
        {"lemma": "differenzieren", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "verb", "gender": None, "phonetic": "dɪfəʁɛnˈtsiːʁən", "translation": "to differentiate / distinguish / membedakan secara teliti", "definition": "Recognize or ascertain what makes something distinct.", "example_sentence": "Man muss zwischen Ursache und Wirkung differenzieren.", "example_translation": "One must differentiate between cause and effect.", "frequency_rank": 1120},
        {"lemma": "ausschlaggebend", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈaʊ̯sˌʃlaːkˌɡeːbn̩t", "translation": "decisive / crucial / menentukan", "definition": "Having a decisive impact.", "example_sentence": "Seine langjährige Erfahrung war ausschlaggebend für den Wahlsieg.", "example_translation": "His long-standing experience was decisive for the election victory.", "frequency_rank": 990},

        # --- C2 (Mastery / Proficiency) ---
        {"lemma": "ungeachtet", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "conjunction", "gender": None, "phonetic": "ˈʊnɡəˌʔaxtət", "translation": "notwithstanding / regardless of / kendatipun", "definition": "Formal conjunction expressing absolute concession.", "example_sentence": "Ungeachtet aller Einwände hielt die Kommission an ihrem Beschluss fest.", "example_translation": "Notwithstanding all objections, the commission stood by its decision.", "frequency_rank": 1400},
        {"lemma": "Allgegenwärtigkeit", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "noun", "gender": "die", "phonetic": "alɡeːɡn̩ˈvɛːɐ̯tɪçkaɪ̯t", "translation": "ubiquity / omnipresence / keberadaan serba ada", "definition": "The state of being present everywhere at once.", "example_sentence": "Die Allgegenwärtigkeit digitaler Medien prägt unsere Zeit.", "example_translation": "The ubiquity of digital media characterizes our time.", "frequency_rank": 1850},
        {"lemma": "Epistemologie", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "noun", "gender": "die", "phonetic": "epɪstəmoloˈɡiː", "translation": "epistemology / epistemologi", "definition": "Philosophical theory of the nature and grounds of knowledge.", "example_sentence": "Seine Habilitationsschrift widmet sich der modernen Epistemologie.", "example_translation": "His post-doctoral thesis is dedicated to modern epistemology.", "frequency_rank": 1950},
        {"lemma": "erörtern", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "verb", "gender": None, "phonetic": "ɛɐ̯ˈʔœʁtɐn", "translation": "to debate / deliberate in detail / mengupas tuntas", "definition": "Discuss complex issues exhaustively from multiple angles.", "example_sentence": "Die Sachverständigen erörterten die juristischen Implikationen eingehend.", "example_translation": "The experts discussed the legal implications in detail.", "frequency_rank": 1600},
        {"lemma": "unabdingbar", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈʊnʔapˌdɪŋbaːɐ̯", "translation": "indispensable / imperative / mutlak diperlukan", "definition": "Absolutely necessary and non-negotiable.", "example_sentence": "Wissenschaftliche Integrität ist unabdingbar für den gesellschaftlichen Diskurs.", "example_translation": "Scientific integrity is indispensable for social discourse.", "frequency_rank": 1520},
    ],
}

async def generate_and_save_data():
    """Generates json word lists per language if needed."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for lang_code, words in LEXICON_DEFINITIONS.items():
        file_path = DATA_DIR / f"{lang_code}.json"
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(words, f, ensure_ascii=False, indent=2)
        logger.info(f"Saved {len(words)} words for {lang_code} to {file_path}")

if __name__ == "__main__":
    asyncio.run(generate_and_save_data())
