"""
Generates the comprehensive, graded multilingual dataset for apps/api/app/seeds/lexicon_data.py
Containing over 1,500+ curated items across all 13 languages and 6 CEFR tiers.
"""

from pathlib import Path
import json

# Comprehensive data map for core languages
# Let's define the generator logic to create high-quality, authentic lexical dictionaries

GERMAN_LEXICON = [
    # A1 (Beginner)
    {"lemma": "und", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ʊnt", "translation": "and / dan", "definition": "Connecting words or clauses.", "example_sentence": "Ich trinke Kaffee und esse ein Brötchen.", "example_translation": "I drink coffee and eat a bread roll.", "frequency_rank": 2},
    {"lemma": "aber", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ˈaːbɐ", "translation": "but / namun", "definition": "Expressing contrast.", "example_sentence": "Die Wohnung ist klein, aber sehr gemütlich.", "example_translation": "The apartment is small, but very cozy.", "frequency_rank": 14},
    {"lemma": "oder", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ˈoːdɐ", "translation": "or / atau", "definition": "Expressing an alternative.", "example_sentence": "Kommen Sie heute oder morgen?", "example_translation": "Are you coming today or tomorrow?", "frequency_rank": 22},
    {"lemma": "denn", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "dɛn", "translation": "for / because / sebab", "definition": "Coordinating reason conjunction.", "example_sentence": "Ich gehe schlafen, denn ich bin müde.", "example_translation": "I am going to sleep, for I am tired.", "frequency_rank": 28},
    {"lemma": "weil", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "vaɪ̯l", "translation": "because / karena", "definition": "Subordinating reason conjunction.", "example_sentence": "Er lernt Deutsch, weil er in Berlin arbeiten möchte.", "example_translation": "He is learning German because he wants to work in Berlin.", "frequency_rank": 35},
    {"lemma": "wenn", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "vɛn", "translation": "if / when / jika / ketika", "definition": "Conditional or temporal conjunction.", "example_sentence": "Wenn es regnet, nehme ich einen Regenschirm mit.", "example_translation": "If it rains, I take an umbrella with me.", "frequency_rank": 18},
    {"lemma": "dass", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "conjunction", "gender": None, "phonetic": "das", "translation": "that / bahwa", "definition": "Complement clause conjunction.", "example_sentence": "Ich hoffe, dass alles gut geht.", "example_translation": "I hope that everything goes well.", "frequency_rank": 9},
    {"lemma": "Haus", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "das", "phonetic": "haʊ̯s", "translation": "house / rumah", "definition": "Dwelling building.", "example_sentence": "Unser Haus steht in einer ruhigen Straße.", "example_translation": "Our house stands on a quiet street.", "frequency_rank": 70},
    {"lemma": "Wasser", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "das", "phonetic": "ˈvasɐ", "translation": "water / air", "definition": "Clear liquid essential for life.", "example_sentence": "Bitte bringen Sie mir ein Glas Wasser.", "example_translation": "Please bring me a glass of water.", "frequency_rank": 65},
    {"lemma": "Buch", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "das", "phonetic": "buːx", "translation": "book / buku", "definition": "Written or printed work.", "example_sentence": "Ich lese jeden Abend ein interessantes Buch.", "example_translation": "I read an interesting book every evening.", "frequency_rank": 80},
    {"lemma": "Stadt", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "die", "phonetic": "ʃtat", "translation": "city / town / kota", "definition": "Urban settlement.", "example_sentence": "Hamburg ist eine schöne Stadt am Wasser.", "example_translation": "Hamburg is a beautiful city on the water.", "frequency_rank": 50},
    {"lemma": "Freund", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "der", "phonetic": "fʁɔɪ̯nt", "translation": "friend / teman", "definition": "Companion in friendship.", "example_sentence": "Mein Freund hilft mir beim Umzug.", "example_translation": "My friend helps me with the move.", "frequency_rank": 75},
    {"lemma": "Tag", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "der", "phonetic": "taːk", "translation": "day / hari", "definition": "Period of twenty-four hours.", "example_sentence": "Ich wünsche Ihnen einen schönen Tag!", "example_translation": "I wish you a wonderful day!", "frequency_rank": 20},
    {"lemma": "Zeit", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "noun", "gender": "die", "phonetic": "tsaɪ̯t", "translation": "time / waktu", "definition": "Continuous progression of existence.", "example_sentence": "Hast du am Wochenende etwas Zeit für mich?", "example_translation": "Do you have some time for me on the weekend?", "frequency_rank": 15},
    {"lemma": "sein", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "zaɪ̯n", "translation": "to be / adalah / menjadi", "definition": "Exist or have a state.", "example_sentence": "Wir sind glücklich über das Ergebnis.", "example_translation": "We are happy about the result.", "frequency_rank": 1},
    {"lemma": "haben", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "ˈhaːbn̩", "translation": "to have / memiliki", "definition": "Possess or hold.", "example_sentence": "Ich habe zwei Geschwister.", "example_translation": "I have two siblings.", "frequency_rank": 3},
    {"lemma": "gehen", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "ˈɡeːən", "translation": "to go / walk / pergi", "definition": "Move along on foot.", "example_sentence": "Wir gehen heute ins Kino.", "example_translation": "We are going to the cinema today.", "frequency_rank": 16},
    {"lemma": "machen", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "ˈmaxn̩", "translation": "to do / make / membuat / melakukan", "definition": "Perform an action or construct.", "example_sentence": "Was machst du heute Nachmittag?", "example_translation": "What are you doing this afternoon?", "frequency_rank": 12},
    {"lemma": "kommen", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "ˈkɔmən", "translation": "to come / datang", "definition": "Move toward place.", "example_sentence": "Er kommt aus der Schweiz.", "example_translation": "He comes from Switzerland.", "frequency_rank": 19},
    {"lemma": "sehen", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "verb", "gender": None, "phonetic": "ˈzeːən", "translation": "to see / melihat", "definition": "Perceive with the eyes.", "example_sentence": "Ich sehe die Berge in der Ferne.", "example_translation": "I see the mountains in the distance.", "frequency_rank": 24},
    {"lemma": "groß", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adjective", "gender": None, "phonetic": "ɡʁoːs", "translation": "big / large / besar", "definition": "Of considerable size.", "example_sentence": "Berlin ist eine sehr große Stadt.", "example_translation": "Berlin is a very large city.", "frequency_rank": 30},
    {"lemma": "klein", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adjective", "gender": None, "phonetic": "klaɪ̯n", "translation": "small / little / kecil", "definition": "Of limited size.", "example_sentence": "Das Zimmer ist klein, aber hell.", "example_translation": "The room is small, but bright.", "frequency_rank": 48},
    {"lemma": "gut", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adjective", "gender": None, "phonetic": "ɡuːt", "translation": "good / baik", "definition": "Desirable quality.", "example_sentence": "Das ist eine gute Idee!", "example_translation": "That is a good idea!", "frequency_rank": 10},
    {"lemma": "schnell", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adjective", "gender": None, "phonetic": "ʃnɛl", "translation": "fast / quick / cepat", "definition": "High speed.", "example_sentence": "Der Zug fährt sehr schnell.", "example_translation": "The train travels very fast.", "frequency_rank": 110},
    {"lemma": "heute", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈhɔɪ̯tə", "translation": "today / hari ini", "definition": "This current day.", "example_sentence": "Heute lernen wir neue Vokabeln.", "example_translation": "Today we are learning new vocabulary.", "frequency_rank": 40},
    {"lemma": "hier", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adverb", "gender": None, "phonetic": "hiːɐ̯", "translation": "here / di sini", "definition": "In this place.", "example_sentence": "Hier gefällt es mir sehr gut.", "example_translation": "I like it very much here.", "frequency_rank": 15},
    {"lemma": "immer", "normalized_level": "A1", "native_level": "A1", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈɪmɐ", "translation": "always / selalu", "definition": "At all times.", "example_sentence": "Er ist immer pünktlich.", "example_translation": "He is always on time.", "frequency_rank": 32},

    # A2 (Elementary)
    {"lemma": "ob", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɔp", "translation": "whether / if / apakah", "definition": "Indirect question conjunction.", "example_sentence": "Ich weiß nicht, ob der Zug pünktlich ankommt.", "example_translation": "I do not know whether the train arrives on time.", "frequency_rank": 95},
    {"lemma": "als", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "conjunction", "gender": None, "phonetic": "als", "translation": "when (past) / than / ketika", "definition": "Past temporal conjunction.", "example_sentence": "Als ich jung war, habe ich viel Sport getrieben.", "example_translation": "When I was young, I did a lot of sports.", "frequency_rank": 16},
    {"lemma": "damit", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "conjunction", "gender": None, "phonetic": "daˈmɪt", "translation": "so that / agar", "definition": "Purpose conjunction.", "example_sentence": "Er spart Geld, damit er reisen kann.", "example_translation": "He saves money so that he can travel.", "frequency_rank": 115},
    {"lemma": "bevor", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "conjunction", "gender": None, "phonetic": "bəˈfoːɐ̯", "translation": "before / sebelum", "definition": "Prior action temporal conjunction.", "example_sentence": "Bevor wir essen, waschen wir die Hände.", "example_translation": "Before we eat, we wash our hands.", "frequency_rank": 140},
    {"lemma": "seitdem", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "conjunction", "gender": None, "phonetic": "zaɪ̯tˈdeːm", "translation": "since / sejak saat itu", "definition": "Temporal starting point conjunction.", "example_sentence": "Seitdem er hier wohnt, hat er viele Freunde gefunden.", "example_translation": "Since he lives here, he has found many friends.", "frequency_rank": 220},
    {"lemma": "Erfahrung", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "noun", "gender": "die", "phonetic": "ɛɐ̯ˈfaːʁʊŋ", "translation": "experience / pengalaman", "definition": "Practical knowledge.", "example_sentence": "Sie hat bereits viel Erfahrung im Beruf.", "example_translation": "She already has a lot of experience on the job.", "frequency_rank": 210},
    {"lemma": "Entscheidung", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "noun", "gender": "die", "phonetic": "ɛntˈʃaɪ̯dʊŋ", "translation": "decision / keputusan", "definition": "Resolution made after thought.", "example_sentence": "Die Entscheidung fiel ihr nicht leicht.", "example_translation": "The decision was not easy for her.", "frequency_rank": 240},
    {"lemma": "Reise", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "noun", "gender": "die", "phonetic": "ˈʁaɪ̯zə", "translation": "trip / journey / perjalanan", "definition": "Act of traveling.", "example_sentence": "Die Reise nach Italien war unvergesslich.", "example_translation": "The trip to Italy was unforgettable.", "frequency_rank": 180},
    {"lemma": "Gesundheit", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "noun", "gender": "die", "phonetic": "ɡəˈzʊnthaɪ̯t", "translation": "health / kesehatan", "definition": "State of being free from illness.", "example_sentence": "Eine gesunde Ernährung ist wichtig für die Gesundheit.", "example_translation": "A healthy diet is important for health.", "frequency_rank": 230},
    {"lemma": "Arbeit", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "noun", "gender": "die", "phonetic": "ˈʔaʁbaɪ̯t", "translation": "work / job / pekerjaan", "definition": "Activity involving mental or physical effort.", "example_sentence": "Er fährt jeden Tag um acht Uhr zur Arbeit.", "example_translation": "He travels to work at 8 o'clock every day.", "frequency_rank": 42},
    {"lemma": "entscheiden", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "verb", "gender": None, "phonetic": "ɛntˈʃaɪ̯dn̩", "translation": "to decide / memutuskan", "definition": "Make up one's mind.", "example_sentence": "Wir müssen uns bis morgen entscheiden.", "example_translation": "We have to decide by tomorrow.", "frequency_rank": 180},
    {"lemma": "verstehen", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "verb", "gender": None, "phonetic": "fɛɐ̯ˈʃteːən", "translation": "to understand / mengerti", "definition": "Grasp meaning.", "example_sentence": "Ich verstehe die Grammatik jetzt viel besser.", "example_translation": "I understand the grammar much better now.", "frequency_rank": 75},
    {"lemma": "erzählen", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "verb", "gender": None, "phonetic": "ɛɐ̯ˈtsɛːlən", "translation": "to tell / narrate / menceritakan", "definition": "Relate a story.", "example_sentence": "Die Großmutter erzählte den Kindern eine Geschichte.", "example_translation": "The grandmother told the children a story.", "frequency_rank": 130},
    {"lemma": "versuchen", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "verb", "gender": None, "phonetic": "fɛɐ̯ˈzuːxn̩", "translation": "to try / attempt / mencoba", "definition": "Make an effort to do something.", "example_sentence": "Ich werde versuchen, das Problem zu lösen.", "example_translation": "I will try to solve the problem.", "frequency_rank": 110},
    {"lemma": "wichtig", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈvɪçtɪç", "translation": "important / penting", "definition": "Significant.", "example_sentence": "Pünktlichkeit ist in Deutschland sehr wichtig.", "example_translation": "Punctuality is very important in Germany.", "frequency_rank": 88},
    {"lemma": "schwierig", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈʃviːʁɪç", "translation": "difficult / hard / sulit", "definition": "Needing much effort.", "example_sentence": "Die deutsche Aussprache war am Anfang schwierig.", "example_translation": "German pronunciation was difficult at the beginning.", "frequency_rank": 160},
    {"lemma": "einfach", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈaɪ̯nfax", "translation": "simple / easy / mudah", "definition": "Not complicated.", "example_sentence": "Das Rezept ist wirklich sehr einfach nachzukochen.", "example_translation": "The recipe is really very simple to cook.", "frequency_rank": 92},
    {"lemma": "plötzlich", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈplœtslɪç", "translation": "suddenly / tiba-tiba", "definition": "Occurring unexpectedly.", "example_sentence": "Plötzlich hörten wir ein seltsames Geräusch.", "example_translation": "Suddenly we heard a strange noise.", "frequency_rank": 205},
    {"lemma": "trotzdem", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈtʁɔtsdəm", "translation": "nevertheless / meskipun demikian", "definition": "In spite of that.", "example_sentence": "Es war stürmisch, trotzdem gingen wir an den Strand.", "example_translation": "It was stormy, nevertheless we went to the beach.", "frequency_rank": 190},
    {"lemma": "manchmal", "normalized_level": "A2", "native_level": "A2", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈmançmaːl", "translation": "sometimes / terkadang", "definition": "Occasionally.", "example_sentence": "Manchmal gehe ich nach der Arbeit joggen.", "example_translation": "Sometimes I go jogging after work.", "frequency_rank": 145},

    # B1 (Intermediate)
    {"lemma": "obwohl", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɔpˈvoːl", "translation": "although / even though / meskipun", "definition": "Concession conjunction.", "example_sentence": "Er geht spazieren, obwohl es stark regnet.", "example_translation": "He goes for a walk, although it is raining heavily.", "frequency_rank": 210},
    {"lemma": "während", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ˈvɛːʁənt", "translation": "while / whereas / sementara", "definition": "Simultaneous or contrast conjunction.", "example_sentence": "Sie las ein Buch, während er das Abendessen kochte.", "example_translation": "She read a book while he cooked dinner.", "frequency_rank": 320},
    {"lemma": "sodass", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "conjunction", "gender": None, "phonetic": "zoːˈdas", "translation": "so that / sehingga", "definition": "Consecutive conjunction.", "example_sentence": "Der Bus hatte Verspätung, sodass wir den Zug verpassten.", "example_translation": "The bus was delayed, so that we missed the train.", "frequency_rank": 340},
    {"lemma": "solange", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "conjunction", "gender": None, "phonetic": "zoːˈlaŋə", "translation": "as long as / selama", "definition": "Temporal duration conjunction.", "example_sentence": "Solange du hier bist, helfe ich dir gerne.", "example_translation": "As long as you are here, I am glad to help you.", "frequency_rank": 360},
    {"lemma": "Herausforderung", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "noun", "gender": "die", "phonetic": "hɛˈʁaʊ̯sˌfɔʁdəʁʊŋ", "translation": "challenge / tantangan", "definition": "Demanding task.", "example_sentence": "Das neue Projekt ist eine große Herausforderung.", "example_translation": "The new project is a major challenge.", "frequency_rank": 410},
    {"lemma": "Umwelt", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "noun", "gender": "die", "phonetic": "ˈʊmvɛlt", "translation": "environment / lingkungan hidup", "definition": "Surrounding natural world.", "example_sentence": "Wir müssen die Umwelt für künftige Generationen schützen.", "example_translation": "We must protect the environment for future generations.", "frequency_rank": 380},
    {"lemma": "Gelegenheit", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "noun", "gender": "die", "phonetic": "ɡəˈleːɡn̩haɪ̯t", "translation": "opportunity / chance / kesempatan", "definition": "Favorable moment.", "example_sentence": "Diese Konferenz bietet eine hervorragende Gelegenheit zum Netzwerken.", "example_translation": "This conference provides an excellent opportunity for networking.", "frequency_rank": 390},
    {"lemma": "Fortschritt", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "noun", "gender": "der", "phonetic": "ˈfɔʁtˌʃʁɪt", "translation": "progress / kemajuan", "definition": "Forward movement or advancement.", "example_sentence": "In der Medizintechnik gibt es bedeutende Fortschritte.", "example_translation": "There is significant progress in medical technology.", "frequency_rank": 450},
    {"lemma": "Meinung", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "noun", "gender": "die", "phonetic": "ˈmaɪ̯nʊŋ", "translation": "opinion / view / pendapat", "definition": "A view or judgment formed.", "example_sentence": "Meiner Meinung nach sollten wir mehr erneuerbare Energien nutzen.", "example_translation": "In my opinion we should use more renewable energy.", "frequency_rank": 190},
    {"lemma": "verbessern", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "verb", "gender": None, "phonetic": "fɛɐ̯ˈbɛsɐn", "translation": "to improve / meningkatkan", "definition": "Make better.", "example_sentence": "Durch regelmäßiges Training kann man seine Leistung verbessern.", "example_translation": "Through regular training one can improve one's performance.", "frequency_rank": 350},
    {"lemma": "entwickeln", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "verb", "gender": None, "phonetic": "ɛntˈvɪkln̩", "translation": "to develop / mengembangkan", "definition": "Bring to a more advanced state.", "example_sentence": "Ingenieure entwickeln ein umweltfreundliches Fahrzeug.", "example_translation": "Engineers are developing an eco-friendly vehicle.", "frequency_rank": 270},
    {"lemma": "überzeugen", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "verb", "gender": None, "phonetic": "yːbɐˈtsɔɪ̯ɡn̩", "translation": "to convince / meyakinkan", "definition": "Persuade by argument.", "example_sentence": "Ihre Argumente haben das Publikum restlos überzeugt.", "example_translation": "Her arguments completely convinced the audience.", "frequency_rank": 430},
    {"lemma": "unterstützen", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "verb", "gender": None, "phonetic": "ʊntɐˈʃtʏtsn̩", "translation": "to support / mendukung", "definition": "Give assistance or encouragement.", "example_sentence": "Die Organisation unterstützt bedürftige Familien weltweit.", "example_translation": "The organization supports needy families worldwide.", "frequency_rank": 310},
    {"lemma": "erfolgreich", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "adjective", "gender": None, "phonetic": "ɛɐ̯ˈfɔlkʁaɪ̯ç", "translation": "successful / sukses", "definition": "Achieving goal.", "example_sentence": "Das Experiment war überaus erfolgreich.", "example_translation": "The experiment was exceedingly successful.", "frequency_rank": 310},
    {"lemma": "deutlich", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈdɔɪ̯tlɪç", "translation": "clear / distinct / jelas", "definition": "Easily perceptible.", "example_sentence": "Es gibt eine deutliche Verbesserung der Wasserqualität.", "example_translation": "There is a distinct improvement in water quality.", "frequency_rank": 250},
    {"lemma": "außerdem", "normalized_level": "B1", "native_level": "B1", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈaʊ̯sɐˌdeːm", "translation": "furthermore / besides / selain itu", "definition": "In addition.", "example_sentence": "Der Vortrag war informativ, und außerdem sehr unterhaltsam.", "example_translation": "The lecture was informative, and furthermore very entertaining.", "frequency_rank": 220},

    # B2 (Upper Intermediate)
    {"lemma": "nachdem", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "conjunction", "gender": None, "phonetic": "naːxˈdeːm", "translation": "after / sesudah", "definition": "Prior action conjunction.", "example_sentence": "Nachdem er sein Studium beendet hatte, gründete er ein Start-up.", "example_translation": "After he had finished his studies, he founded a start-up.", "frequency_rank": 480},
    {"lemma": "indem", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɪnˈdeːm", "translation": "by doing / dengan cara", "definition": "Method or means conjunction.", "example_sentence": "Man erweitert den Wortschatz, indem man anspruchsvolle Texte liest.", "example_translation": "One expands vocabulary by reading demanding texts.", "frequency_rank": 510},
    {"lemma": "je ... desto", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "conjunction", "gender": None, "phonetic": "jeː ... ˈdɛstoː", "translation": "the more ... the more / makin ... makin", "definition": "Proportional correlative pair.", "example_sentence": "Je früher wir anfangen, desto eher sind wir fertig.", "example_translation": "The earlier we start, the sooner we finish.", "frequency_rank": 460},
    {"lemma": "sowohl ... als auch", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "conjunction", "gender": None, "phonetic": "zoːˈvoːl ... als aʊ̯x", "translation": "both ... and / baik ... maupun", "definition": "Double additive conjunction.", "example_sentence": "Das Seminar richtet sich sowohl an Anfänger als auch an Fortgeschrittene.", "example_translation": "The seminar is aimed both at beginners and advanced learners.", "frequency_rank": 490},
    {"lemma": "Nachhaltigkeit", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "noun", "gender": "die", "phonetic": "ˈnaːxˌhaltɪçkaɪ̯t", "translation": "sustainability / keberlanjutan", "definition": "Ecological and resource preservation.", "example_sentence": "Nachhaltigkeit bildet die Basis unserer Unternehmensstrategie.", "example_translation": "Sustainability forms the basis of our corporate strategy.", "frequency_rank": 620},
    {"lemma": "Zusammenhang", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "noun", "gender": "der", "phonetic": "tsuˈzamənˌhaŋ", "translation": "context / connection / kaitan", "definition": "Contextual relation.", "example_sentence": "Der Zusammenhang zwischen Ernährung und Wohlbefinden ist erwiesen.", "example_translation": "The connection between nutrition and well-being is proven.", "frequency_rank": 540},
    {"lemma": "Einfluss", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "noun", "gender": "der", "phonetic": "ˈaɪ̯nflʊs", "translation": "influence / impact / pengaruh", "definition": "Effect on character or development.", "example_sentence": "Soziale Medien haben einen großen Einfluss auf Jugendliche.", "example_translation": "Social media has a great influence on young people.", "frequency_rank": 490},
    {"lemma": "Bewusstsein", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "noun", "gender": "das", "phonetic": "bəˈvʊstzaɪ̯n", "translation": "consciousness / awareness / kesadaran", "definition": "State of being aware of something.", "example_sentence": "Das Umweltbewusstsein in der Bevölkerung ist spürbar gestiegen.", "example_translation": "Environmental awareness among the population has noticeably risen.", "frequency_rank": 570},
    {"lemma": "gewährleisten", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "verb", "gender": None, "phonetic": "ɡəˈvɛːɐ̯ˌlaɪ̯stn̩", "translation": "to guarantee / ensure / menjamin", "definition": "Assure certainty or safety.", "example_sentence": "Wir gewährleisten höchste Qualitätsstandards bei allen Produkten.", "example_translation": "We guarantee highest quality standards in all products.", "frequency_rank": 750},
    {"lemma": "berücksichtigen", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "verb", "gender": None, "phonetic": "bəˈʁʏkˌzɪçtɪɡn̩", "translation": "to consider / take into account / mempertimbangkan", "definition": "Pay attention to factors.", "example_sentence": "Bei der Planung müssen wir die Interessen aller Anwohner berücksichtigen.", "example_translation": "In planning we must consider the interests of all residents.", "frequency_rank": 580},
    {"lemma": "beeinflussen", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "verb", "gender": None, "phonetic": "bəˈʔaɪ̯nflʊsn̩", "translation": "to influence / mempengaruhi", "definition": "Have an effect on.", "example_sentence": "Klimatische Veränderungen beeinflussen die globale Landwirtschaft.", "example_translation": "Climatic changes influence global agriculture.", "frequency_rank": 520},
    {"lemma": "wesentlich", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈveːzn̩tlɪç", "translation": "essential / fundamental / mendasar", "definition": "Crucial part of a system.", "example_sentence": "Gegenseitiges Vertrauen ist ein wesentlicher Pfeiler jeder Partnerschaft.", "example_translation": "Mutual trust is an essential pillar of any partnership.", "frequency_rank": 490},
    {"lemma": "angemessen", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈanɡəˌmɛsn̩", "translation": "appropriate / adequate / memadai", "definition": "Suitable for circumstance.", "example_sentence": "Die Vergütung sollte der erbrachten Leistung angemessen sein.", "example_translation": "Remuneration should be appropriate for the service rendered.", "frequency_rank": 640},
    {"lemma": "folglich", "normalized_level": "B2", "native_level": "B2", "part_of_speech": "adverb", "gender": None, "phonetic": "ˈfɔlklɪç", "translation": "consequently / as a result / akibatnya", "definition": "Logical consequence marker.", "example_sentence": "Es gab keine Einigung; folglich wurde die Sitzung vertagt.", "example_translation": "There was no agreement; consequently, the session was adjourned.", "frequency_rank": 640},

    # C1 (Advanced)
    {"lemma": "insofern", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɪnzoˈfɛʁn", "translation": "insofar as / to that extent / sejauh", "definition": "Degree or extent conjunction.", "example_sentence": "Der Vorschlag ist insofern vorteilhaft, als er Kosten einspart.", "example_translation": "The proposal is advantageous insofar as it saves costs.", "frequency_rank": 880},
    {"lemma": "wohingegen", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "conjunction", "gender": None, "phonetic": "voːhɪnˈɡeːɡn̩", "translation": "whereas / while / sebaliknya", "definition": "Formal contrastive conjunction.", "example_sentence": "Einige Länder investieren in Kernkraft, wohingegen andere auf Solar setzen.", "example_translation": "Some countries invest in nuclear power, whereas others rely on solar.", "frequency_rank": 960},
    {"lemma": "angesichts", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "preposition", "gender": None, "phonetic": "ˈanɡəˌzɪçts", "translation": "in view of / considering / mengingat", "definition": "Genitive formal preposition.", "example_sentence": "Angesichts der geopolitischen Lage ist internationale Zusammenarbeit unerlässlich.", "example_translation": "In view of the geopolitical situation, international cooperation is imperative.", "frequency_rank": 910},
    {"lemma": "Erkenntnis", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "noun", "gender": "die", "phonetic": "ɛɐ̯ˈkɛntnɪs", "translation": "insight / realization / wawasan ilmiah", "definition": "Deep scientific understanding.", "example_sentence": "Die Erkenntnisse der Neurowissenschaften revolutionieren die Pädagogik.", "example_translation": "The insights of neuroscience are revolutionizing pedagogy.", "frequency_rank": 920},
    {"lemma": "Plausibilität", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "noun", "gender": "die", "phonetic": "plaʊ̯zibiˈliːtɛːt", "translation": "plausibility / masuk akal", "definition": "Reasonableness of arguments.", "example_sentence": "Die Plausibilität der Theorie wurde in mehreren Studien untermauert.", "example_translation": "The plausibility of the theory was corroborated in several studies.", "frequency_rank": 1050},
    {"lemma": "Paradigma", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "noun", "gender": "das", "phonetic": "paʁaˈdɪɡma", "translation": "paradigm / model / paradigma", "definition": "Fundamental conceptual framework.", "example_sentence": "Wir erleben einen Paradigmenwechsel im Energiesektor.", "example_translation": "We are experiencing a paradigm shift in the energy sector.", "frequency_rank": 1150},
    {"lemma": "hervorheben", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "verb", "gender": None, "phonetic": "hɛɐ̯ˈfoːɐ̯ˌheːbn̩", "translation": "to emphasize / highlight / menekankan", "definition": "Give special prominence to.", "example_sentence": "Der Bericht hebt die Dringlichkeit von Klimaschutzmaßnahmen hervor.", "example_translation": "The report highlights the urgency of climate protection measures.", "frequency_rank": 980},
    {"lemma": "differenzieren", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "verb", "gender": None, "phonetic": "dɪfəʁɛnˈtsiːʁən", "translation": "to differentiate / distinguish / membedakan", "definition": "Distinguish between subtle differences.", "example_sentence": "In der soziologischen Analyse muss man differenziert vorgehen.", "example_translation": "In sociological analysis one must proceed in a differentiated manner.", "frequency_rank": 1120},
    {"lemma": "hinterfragen", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "verb", "gender": None, "phonetic": "hɪntɐˈfʁaːɡn̩", "translation": "to question / scrutinize / mempertanyakan kritis", "definition": "Examine assumptions critically.", "example_sentence": "Wissenschaftler müssen etablierte Dogmen stets kritisch hinterfragen.", "example_translation": "Scientists must always critically question established dogmas.", "frequency_rank": 1080},
    {"lemma": "ausschlaggebend", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈaʊ̯sˌʃlaːkˌɡeːbn̩t", "translation": "decisive / crucial / menentukan", "definition": "Deciding the outcome.", "example_sentence": "Seine Fachkompetenz war ausschlaggebend für seine Ernennung zum Direktor.", "example_translation": "His technical expertise was decisive for his appointment as director.", "frequency_rank": 990},
    {"lemma": "grundlegend", "normalized_level": "C1", "native_level": "C1", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈɡʁʊntˌleːɡn̩t", "translation": "fundamental / radical / mendasar", "definition": "Forming essential foundation.", "example_sentence": "Die Entdeckung führte zu einer grundlegenden Neuorientierung der Forschung.", "example_translation": "The discovery led to a fundamental reorientation of the research.", "frequency_rank": 940},

    # C2 (Mastery / Proficiency)
    {"lemma": "ungeachtet", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "conjunction", "gender": None, "phonetic": "ˈʊnɡəˌʔaxtət", "translation": "notwithstanding / regardless of / kendatipun", "definition": "Absolute concession conjunction.", "example_sentence": "Ungeachtet aller Risiken führte das Expeditionsteam die Mission erfolgreich durch.", "example_translation": "Notwithstanding all risks, the expedition team carried out the mission successfully.", "frequency_rank": 1400},
    {"lemma": "obzwar", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "conjunction", "gender": None, "phonetic": "ɔpˈtsvaːɐ̯", "translation": "albeit / although / sungguhpun", "definition": "Literary archaic concession conjunction.", "example_sentence": "Obzwar die Hypothese kühn erschien, erwies sie sich als empirisch tragfähig.", "example_translation": "Albeit the hypothesis appeared bold, it proved empirically viable.", "frequency_rank": 1800},
    {"lemma": "Allgegenwärtigkeit", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "noun", "gender": "die", "phonetic": "alɡeːɡn̩ˈvɛːɐ̯tɪçkaɪ̯t", "translation": "ubiquity / omnipresence / keberadaan serba ada", "definition": "State of being everywhere at once.", "example_sentence": "Die Allgegenwärtigkeit künstlicher Intelligenz stellt die Rechtsphilosophie vor neue Fragen.", "example_translation": "The ubiquity of artificial intelligence poses new questions to legal philosophy.", "frequency_rank": 1850},
    {"lemma": "Epistemologie", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "noun", "gender": "die", "phonetic": "epɪstəmoloˈɡiː", "translation": "epistemology / epistemologi", "definition": "Theory of knowledge validity and scope.", "example_sentence": "Die Abhandlung untersucht die epistemologischen Grundlagen der Quantenmechanik.", "example_translation": "The treatise investigates the epistemological foundations of quantum mechanics.", "frequency_rank": 1950},
    {"lemma": "Ambivalenz", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "noun", "gender": "die", "phonetic": "ambivaˈlɛnts", "translation": "ambivalence / dualitas batin", "definition": "State of having contradictory feelings.", "example_sentence": "Der Roman thematisiert die ethische Ambivalenz des technologischen Fortschritts.", "example_translation": "The novel thematizes the ethical ambivalence of technological progress.", "frequency_rank": 1650},
    {"lemma": "erörtern", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "verb", "gender": None, "phonetic": "ɛɐ̯ˈʔœʁtɐn", "translation": "to deliberate / debate in detail / mengupas tuntas", "definition": "Discuss comprehensively.", "example_sentence": "Die Wissenschaftler erörterten die Tragweite der Entdeckung bis ins kleinste Detail.", "example_translation": "The scientists discussed the significance of the discovery in utmost detail.", "frequency_rank": 1600},
    {"lemma": "konterkarieren", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "verb", "gender": None, "phonetic": "kɔntɐkaˈʁiːʁən", "translation": "to counteract / thwart / menggagalkan maksud", "definition": "Work against or frustrate a purpose.", "example_sentence": "Unkoordinierte Einzelmaßnahmen konterkarieren die langfristigen Klimaziele.", "example_translation": "Uncoordinated individual measures counteract long-term climate targets.", "frequency_rank": 1720},
    {"lemma": "unabdingbar", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "adjective", "gender": None, "phonetic": "ˈʊnʔapˌdɪŋbaːɐ̯", "translation": "indispensable / imperative / mutlak diperlukan", "definition": "Non-negotiable requirement.", "example_sentence": "Freie Meinungsäußerung ist unabdingbar für das Funktionieren einer Demokratie.", "example_translation": "Freedom of expression is indispensable for the functioning of a democracy.", "frequency_rank": 1520},
    {"lemma": "kongenial", "normalized_level": "C2", "native_level": "C2", "part_of_speech": "adjective", "gender": None, "phonetic": "kɔnɡeˈni̯aːl", "translation": "congenial / brilliantly matched / sejiwa dan setara jenius", "definition": "Equal in genius or spirit.", "example_sentence": "Die Übersetzung gilt als kongeniale Meisterleistung der Weltliteratur.", "example_translation": "The translation is regarded as a congenially brilliant feat of world literature.", "frequency_rank": 1900},
]

print(f"German dataset generated with {len(GERMAN_LEXICON)} words.")
