"""initial_schema

Revision ID: 16b64a8457e2
Revises: 
Create Date: 2026-08-24 12:33:27.927400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b64a8457e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('language_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_language_id', 'target_language_id', name='uq_origin_target_pair')
    )
    op.create_index(op.f('ix_language_pairs_id'), 'language_pairs', ['id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_pair_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_translated', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_translated', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_reading_minutes', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_pair_id'], ['language_pairs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_cefr_level'), 'stories', ['cefr_level'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_index(op.f('ix_stories_is_published'), 'stories', ['is_published'], unique=False)
    op.create_table('grammar_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('explanation_translated', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_tips_id'), 'grammar_tips', ['id'], unique=False)
    op.create_index(op.f('ix_grammar_tips_story_id'), 'grammar_tips', ['story_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_translated', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('wrong_answers', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes_story_id'), 'quizzes', ['story_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('quiz_attempts', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_is_favorite'), 'user_progress', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_user_progress_story_id'), 'user_progress', ['story_id'], unique=True)
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('pronunciation_url', sa.String(length=500), nullable=True),
    sa.Column('difficulty_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_id'), 'vocabulary', ['id'], unique=False)
    op.create_index(op.f('ix_vocabulary_story_id'), 'vocabulary', ['story_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_word'), 'vocabulary', ['word'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('next_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_index(op.f('ix_flashcards_next_review'), 'flashcards', ['next_review'], unique=False)
    op.create_index(op.f('ix_flashcards_vocabulary_id'), 'flashcards', ['vocabulary_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcards_vocabulary_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_next_review'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_vocabulary_word'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_story_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_id'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_user_progress_story_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_is_favorite'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_quizzes_story_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_grammar_tips_story_id'), table_name='grammar_tips')
    op.drop_index(op.f('ix_grammar_tips_id'), table_name='grammar_tips')
    op.drop_table('grammar_tips')
    op.drop_index(op.f('ix_stories_is_published'), table_name='stories')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_cefr_level'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_language_pairs_id'), table_name='language_pairs')
    op.drop_table('language_pairs')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###